### ISSUE TITLE
добавить больше тегов в описание репозитория чтобы он легче находился

### ISSUE THREAD

**Issue by antonsoroko** [azzzak/alice#2]
поиск очевидными тегами не показывает этот репозиторий, но показывает ваши смежные репы (так и нашел)
https://github.com/topics/yandex-dialogs?l=go

предлагаю добавить хотя бы

yandex-dialogs
yandex-alice

что бы репозиторий было проще найти.

спасибо.

**Comment by azzzak** [comment]
добавлю, не вопрос.

на самом деле, ниша узенькая и все заметные проекты, связанные с алисой, есть в списке [Awesome Alice](https://github.com/sameoldmadness/awesome-alice). начинать поиск там эффективнее, чем щелкать по тегам.
